Doctors/urls.py
from django.urls import path
from .views import *

app_name = "Doctors"

urlpatterns = [
    path("<str:inp_user>/info", doctors_user, name="d_user"),
    path('appoint/', doctors_appoint, name="appoint"),
    path('<int:inp_id>/d_update', doctors_update, name="d_update"),
    path('<int:inp_id>/', doctors_byId, name="d_byId"),
    path("d_new/", doctors_new, name="d_new"),
    path("d_all/", doctors_all, name="d_all")
]

Patients/urls.py
from django.urls import path
from .views import *

app_name="Patients"
urlpatterns = [
				
				path("<int:inp_id>/p_update", patients_update, name="p_update"),
				path("<int:inp_id>/p_delete", patients_delete, name="p_delete"),
				path("<int:inp_id>/", patients_byId, name="p_byId"),
				path("p_new/", patients_new, name="p_new"),
				path("p_all/", patients_all, name = "p_all")
			  ]

proHMS/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import *
import Doctors.urls
import Patients.urls
from Users_Employees.views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hms/', mainpage, name='hms'),
    path('captcha/', include('captcha.urls')),
    path('home/', homepage, name="home"),
    path('signup/', SignUp, name='signup'),
    path('signin/', SignIn, name='signin'),
    path('signout/', SignOut, name='signout'),
    path('doctors/', include('Doctors.urls', namespace="Doctors")),
    path('patients/', include('Patients.urls', namespace="Patients"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/doctors_all.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
 {{ title }}
{% endblock %}

{% block search %}
	<form class="navbar-form navbar-right">
        <div class="input-group">
         <input type="text" class="form-control" placeholder="Speciality" name="search" value="{{ request.GET.search }}">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
            </div>
        </div>
	</form>
{% endblock%}
{%block home %}
{% endblock %}
{% block body %}
<div class="container doctors-table">

	<h1>Doctors List</h1>
	
	<table class=" table table-bordered">
		<tr>
			<th>Doctor Name</th>
			<th>Address</th>
			<th>Speciality</th>
			<th>Contact No.</th>
			<th>Get Appointment</th>
		</tr>
		{% for each in doctors %}
		<tr>

			<td><a href="{% url 'Doctors:d_byId' each.id %}">{{ each.d_name }}</a></td>
			<td>{{ each.d_address }}</td>
			<td>{{ each.speciality }}</td>
			<td>{{ each.contact_no }}</td>
			<td><button><a href="{% url 'Doctors:appoint'%}">Appoint</a></button></td>
		</tr>
		{% endfor %}
	</table>
	<button class="d_new"><a href="{% url 'Doctors:d_new'%}">Add doctor</a></button>
</div>
{% endblock %}

templates/doctors_appoint.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
 {{ title }}
{% endblock %}
{%block home %}
{% endblock %}
{% block body %}
	<form method="POST">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" name="" value="Get Appoint">
	</form>
{% endblock %}

templates/doctors_byId.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
 {{ title }}
{% endblock %}
{%block home %}
{% endblock %}
{% block body %}
<div class="container doctors-table">

	<h1>Doctor Detail</h1>
	
	<table class="table-bordered table">
		<tr>
			<th>Photo</th>
			<th>Doctor Name</th>
			<th>Address</th>
			<th>Speciality</th>
			<th>Contact No.</th>
			<th>Get Appointment</th>
		</tr>
		
		<tr>
			<td>
			{% if doctor.image %}
				<img src="{{ doctor.image.url }}">
			{% endif %}
			</td>

			<td>{{ doctor.d_name }}</td>
			<td>{{ doctor.d_address }}</td>
			<td>{{ doctor.speciality }}</td>
			<td>{{ doctor.contact_no}}</td>
			<td><button><a href="#">Appoint</a></button></td>
		</tr>
		
	</table>
	<button><a href="{% url 'Doctors:d_update' doctor.id %}">Update</a></button>
</div>
{% endblock %}

templates/doctors_new.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
 {{ title }}
{% endblock %}
{%block home %}
{% endblock %}
{% block body %}
<div class="container">
<form method="POST" class="doctor-form">{% csrf_token %}
	<h1>Doctor's details!!</h1>
	<table class="table-bordered">
		<tr>
			<td><label for="name">Doctor's Name:</label></td>
			<td><input type="text" name="{{ form.d_name.html_name }}" id="name" required></td>
		</tr>
		<tr>
			<td><label>Address:</label></td>
			<td><input type="text" name="{{ form.d_address.html_name }}" required></td>
		</tr>
		<tr>
			<td><label>Contact No.</label></td>
			<td><input type="text" name="{{ form.contact_no.html_name }}" required></td>
		</tr>
		<tr>
			<td><label>Speciality:</label></td>
			<td><input type="text" name="{{ form.speciality.html_name }}" required></td>
		</tr>
		<tr>
			<td><label>Upload Image:</label></td>
			<td>{{ form.image }}</td>
			<td>
				{% if form.errors.image %}
				 	{{ form.errors.image }}
				 {% endif %}
			</td>
		</tr>
	</table>
	<div class="d-reg">
		<button type="submit" class="btn btn-default">Submit</button>
		<button type="reset" class="btn btn-default">Reset</button>	
	</div>
</form>
</div>

{% endblock %}

templates/doctors_update.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
 {{ title }}
{% endblock %}
{%block home %}
{% endblock %}
{% block body %}
<div class="container">
<form method="POST" class="doctor-form">{% csrf_token %}
	<h1>Update Doctor's details!!</h1>
	<table class="table-bordered">
		<tr>
			<td><label for="name">Doctor's Name:</label></td>
			<td><input type="text" value={{ form.d_name.value }} name="{{ form.d_name.html_name }}" id="name"></td>
		</tr>
		<tr>
			<td><label>Address:</label></td>
			<td><input type="text" value={{ form.d_address.value }} name="{{ form.d_address.html_name }}"></td>
		</tr>
		<tr>
			<td><label>Contact No.</label></td>
			<td><input type="text" value={{ form.contact_no.value }} name="{{ form.contact_no.html_name }}"></td>
		</tr>
		<tr>
			<td><label>Speciality:</label></td>
			<td><input type="text" value={{ form.speciality.value }} name="{{ form.speciality.html_name }}"></td>
		</tr>
	</table>
	<div class="d-reg">
		<button type="submit" class="btn btn-default">Submit</button>
		<button type="reset" class="btn btn-default">Reset</button>	
	</div>
</form>
</div>

{% endblock %}

templates/doctors_user.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
 {{ title }}
{% endblock %}

{% block search %}
	<form class="navbar-form navbar-right">
        <div class="input-group">
         <input type="text" class="form-control" placeholder="Speciality" name="search" value="{{ request.GET.search }}">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
            </div>
        </div>
        <button><a href="{% url 'signout'%}">Logout</a></button>
	</form>
{% endblock%}
{%block home %}
{% endblock %}
{% block body %}

	<h1>Doctors List</h1>
	
	<table>
		<tr>
			<th>Doctor Name</th>
			<th>Address</th>
			<th>Speciality</th>
			<th>Contact No.</th>
			<th>Get Appointment</th>
		</tr>
		{% for each in doctors %}
		<tr>
			<td><a href="{% url 'Doctors:d_byId' each.id %}">{{ each.d_name }}</a></td>
			<td>{{ each.d_address }}</td>
			<td>{{ each.speciality }}</td>
			<td>{{ each.contact_no }}</td>
			<td><button><a href="{% url 'Doctors:appoint'%}">Appoint</a></button></td>
		</tr>
		{% endfor %}
	</table>
	<button><a href="{% url 'Doctors:d_new'%}">Add doctor</a></button>
{% endblock %}

templates/homepage.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
 {{ title }}
{% endblock %}
{% block body %}


{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
		{% endblock %}
	</title>
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="wrap-1">
        <div class="container fixed-top">
            <div class="header">
                <a href="#">Hospital Management System</a>
                {% block loginout %}
                <button class="btn logout"><a href="{% url 'signout'%}">Logout</a> <span class="glyphicon glyphicon-log-out"></span></button>
                {% endblock%}
            </div>
            <nav class="navbar navbar-inverse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'home'%}">Home</a></li>
                    <li><a href="{% url 'Patients:p_new'%}">Patient's Registration</a></li>
                    <li><a href="{% url 'Doctors:d_all'%}">Available Doctors</a></li>
                    <li><a href="{% url 'Doctors:d_new'%}">Doctor's Registration</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
                {% block search %}
                <form class="navbar-form navbar-right">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
                {% endblock %}
            </nav>

        </div>

    </div>
    {% block carousel %}
    <div class="wrap-2">
        <div class="container">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="{% static 'img/banner.jpg'%}" alt="Chania">
                        <div class="carousel-caption">
                            <h3>Multi-speciality Hospitals</h3>
                            <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
                        </div>
                    </div>

                    <div class="item">
                        <img src="{% static 'img/bg-1.jpg'%}" alt="Chania">
                        <div class="carousel-caption">
                            <h3>Hi-Tech Theatres</h3>
                            <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
                        </div>
                    </div>

                    <div class="item">
                        <img src="{% static 'img/bg-2.jpg'%}" alt="Flower">
                        <div class="carousel-caption">
                            <h3>Clean &amp; Hygienic ward</h3>
                            <p>Beautiful flowers in Kolymbari, Crete.</p>
                        </div>
                    </div>
                </div>

                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    {% endblock %}
	{% block home %}
        <div class="wrap-3">
        <div class="container">
            <div class="col-sm-8 serv">
                <div class="hospital">
                    <h2>About Hospital</h2>
                    <ul>
                        <li></li>
                    </ul>

                </div>
                <div class="services">
                    <h2>About Services</h2>
                    <ul>
                        <li></li>
                    </ul>

                </div>
            </div>
            <div class="col-sm-4 tip">
                <h3>Important Points!!</h3>
                <ul>
                    <li>hh</li>
                    <li>hh</li>
                    <li>hh</li>
                    <li>hh</li>
                    <li>hh</li>
                    <li>hh</li>
                    <li>hh</li>

                </ul>

            </div>
        </div>
    </div>
	{% endblock %}
    {% block body %}
    {% endblock %}
    <div class="footer">
        <div class="container">
            <div class="row row-no-gutters">
                <div class="col-xs-6">
                    <div class="nav-footer">
                        <ul>
                            <li><a href="{% url 'Patients:p_all'%}">All Patients</a></li>
                            <li><a href="#">All Doctors</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xs-6">
                   <div class="social">
                    <ul>
                        <li><a href="" class="fa fa-facebook"></a></li>
                        <li><a href="" class="fa fa-twitter"></a></li>
                        <li><a href="" class="fa fa-instagram"></a></li>
                        <li><a href="" class="fa fa-pinterest"></a></li>
                    </ul>
                </div>
                </div>
            </div>
        </div>
    </div>



	<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    {% block js %}
    {% endblock %}
</body>
</html>

templates/patients_all.html
{% extends 'layout.html'%}
{% load static %}
{% block title %}
 {{ title }}
{% endblock %}

{% block search %}
	<form class="navbar-form navbar-right">
        <div class="input-group">
         <input type="text" class="form-control" placeholder="Search" name="search" value="{{ request.GET.search }}">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
            </div>
        </div>
	</form>
{% endblock%}
{% block carousel %}
{% endblock %}
{%block home %}
{% endblock %}
{% block body %}
<div class="container">
	<h1>Patients List</h1>
	<table class="table-bordered">
		<tr>
			<th>ID</th>
			<th>Patient Name</th>
			<th>Age</th>
			<th>Sex</th>
			<th>Address</th>
			<th>Disease</th>
			<th>Contact No</th>
			<th>Ward No</th>
			<th>Manage</th>
		</tr>
		{% for each in patients %}
		<tr>
			<td>{{ each.id }}</td>
			<td>{{ each.p_name }}</td>
			<td>{{ each.p_age }}</td>
			<td>{{ each.p_sex }}</td>
			<td>{{ each.p_address }}</td>
			<td>{{ each.disease }}</td>
			<td>{{ each.contact_no}}</td>
			<td>{{ each.ward_no }}</td>
			<td>
				<button><a href="{% url 'Patients:p_update' each.id %}">Update</a></button> 
				<button><a href="{% url 'Patients:p_delete' each.id %}">Delete</a></button>
			</td>
		</tr>
		{% endfor %}
	</table>
	<button><a href="{% url 'Patients:p_new'%}">Add New Patient</a></button>
	<button><a href="{% url 'Doctors:d_all'%}">View Doctors List </a></button>
</div>

{% endblock %}

templates/patients_delete.html
<!DOCTYPE html>
<html>
<head>
	<title> {{ title }}</title>
</head>
<body>
	<h1>{{ heading }}</h1>
	<button><a href="{% url 'Patients:p_all' %}">Patients List</a></button>
</body>
</html>

templates/patients_new.html
{% extends 'layout.html'%}
{% load static %}
{% block title %}
 {{ title }}
{% endblock %}
{%block home %}
{% endblock %}
{% block body %}
<div class="container">
<form method="POST" class="doctor-form">{% csrf_token %}
	<h1>Patient's detail!!</h1>
	<table class="table-bordered">
		<tr>
			<td><label for="name">Patient's Name:</label></td>
			<td><input type="text" name="{{ form.p_name.html_name }}" id="name" required></td>
		</tr>
		<tr>
			<td><label>Age:</label></td>
			<td><input type="text" name="{{ form.p_age.html_name }}" required></td>
		</tr>
		<tr>
			<td><label>Sex:</label></td>
			<td><input type="text" name="{{ form.p_sex.html_name }}" required></td>
		</tr>
		<tr>
			<td><label>Address:</label></td>
			<td><input type="text" name="{{ form.p_address.html_name }}" required></td>
		</tr>
		<tr>
			<td><label>Disease:</label></td>
			<td><input type="text" name="{{ form.disease.html_name }}" required></td>
		</tr>
		<tr>
			<td><label>Contact No.</label></td>
			<td><input type="text" name="{{ form.contact_no.html_name }}" required></td>
		</tr>
		<tr>
			<td><label>Ward No.:</label></td>
			<td><input type="text" name="{{ form.ward_no.html_name }}"></td>
		</tr>
	</table>
	<div class="d-reg">
		<button type="submit" class="btn btn-default">Submit</button>
		<button type="reset" class="btn btn-default">Reset</button>	
	</div>
	
</form>
</div>
{% endblock %}

templates/patients_public.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
 {{ title }}
{% endblock %}


{% block search %}
	<form class="navbar-form navbar-right">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search" name="search" value="{{ request.GET.search }}">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </div>
                    </div>
    </form>
{% endblock%}

{% block body %}
	<h1>Today's Appointments</h1>
	<table>
		<tr>
			<th>ID</th>
			<th>Patient Name</th>
			<th>Age</th>
			<th>Sex</th>
			<th>Contact No</th>
			<th>Manage</th>
		</tr>
		{% for each in patients %}
		<tr>
			<td>{{ each.id }}</td>
			<td>{{ each.p_name }}</td>
			<td>{{ each.p_age }}</td>
			<td>{{ each.p_sex }}</td>
			<td>{{ each.contact_no}}</td>
			<td>
				<button><a href="#">Delete</a></button>
			</td>
		</tr>
		{% endfor %}
	</table>

{% endblock %}

templates/signin.html
{% extends 'outlayout.html' %}
{% block title %}
	{{ title }}
{% endblock %}
{% block carousel %}
{% endblock %}
{% block home %}
{% endblock %}
{% block body %}

{% block loginout %}
{% endblock %}
<div class="container">
	<form method="POST" class="doctor-form">{% csrf_token %}
			<h1>Log In</h1>
			<table>
				<tr>
					<td><label>Username:</label></td>
					<td><input type="text" name="{{ form.username.html_name }}"></td>
				</tr>
				<tr>
					<td><label>Password:</label></td>
					<td><input type="password" name="{{ form.password.html_name }}"></td>
				</tr>	
				<tr>
					<td><label>Enter Captcha:</label></td>
					<td>{{ form.captcha }}</td>
					<td>
					{% if form.errors.captcha %}
						{{ form.errors.captcha }}
					{% endif %}
					</td>
				</tr>			
			</table>
			<div class="d-reg">
				<button type="submit">Login</button>
				<button type="Reset">Reset</button>
			</div>
			<div class="forgot">
				<a href="#">Forgot Password?</a>
				<a href="{% url 'signup'%}">New User?</a>				
			</div>
	</form>
</div>

{% endblock %}

templates/signup.html
{% extends 'outlayout.html '%}
{% block title %}
	{{ title }}
{% endblock %}
{% block carousel %}
{% endblock %}
{% block home %}
{% endblock %}
{% block loginout %}
{% endblock %}
{% block body %}
<div class="container">
	<form method="POST" class="doctor-form">{% csrf_token %}
		<h1>Register details!!!</h1>
			<table>
				<tr>
					<td><label>Username:</label></td>
					<td><input type="text" name="{{ form.username.html_name }}"></td>
				</tr>
				<tr>
					<td><label>Email:</label></td>
					<td><input type="email" name="{{ form.email.html_name }}" class="email"></td>
					<td>
						{% if form.errors.email %}
							{{ form.errors.email }}
						{% endif %}
					</td>
				</tr>
				<tr>
					<td><label>Password:</label></td>
					<td><input type="password" name="{{ form.password.html_name }}"></td>
				</tr>
				<tr>
					<td><label>Confirm Password:</label></td>
					<td><input type="password" name="{{ form.confirm_password.html_name }}"></td>
					<td>
						{% if form.errors.confirm_password %}
							{{ form.errors.confirm_password }}
						{% endif %}
					</td>
				</tr>				
			</table>
			<div class="d-reg">
				<button type="submit" class="submit">Register</button>
				<button type="Reset">Reset</button>
			</div>
			<div class="forgot">
				<a href="{% url 'signin'%}">Already Account?</a>
			</div>
	</form>
</div>
{% block js %}
<script type="text/javascript">
	$(document).ready(function(){
		$(".submit").click(fucntion(){
			if $(".errorlist li").value!=null{
				
			}
		})
	})
</script>
{% endblock %}

{% endblock %}